In [17]:
import pandas as pd

df = pd.read_csv(r'C:\Users\clint\Desktop\Remitances\Data\29.csv')
df

,Sending_Country,Receiving_Country,Year,Value,Unit,Source,Region,Sending_Country_Code,Receiving_Country_Code,Sending_Country_GDP,Receiving_Country_GDP,Sending_Country_GDP_Per_Capita,Receiving_Country_GDP_Per_Capita
0,Algeria,Senegal,2021,0.183414825,USD millions,BCEAO,Africa,DZA,SEN,1.994889e+05,2.435960e+04,4456.746876,1414.539511
1,Australia,Ethiopia,2020,13.59617511,USD millions,National Bank of Ethiopia,Africa,AUS,ETH,1.491063e+06,9.507178e+04,58132.798520,799.475595
2,Australia,Kenya,2024,"184,497.099695719",USD millions,Central Bank of Kenya,Africa,AUS,KEN,1.665258e+06,1.045752e+05,61211.896760,1853.087855
3,Australia,Uganda,2022,22,USD millions,Bank of Uganda,Africa,AUS,UGA,1.587133e+06,4.414722e+04,61009.807710,933.094056
4,Austria,Kenya,2024,"13,169.065145833",USD millions,Central Bank of Kenya,Africa,AUT,KEN,4.181904e+05,1.045752e+05,45562.040690,1853.087855
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3975,Suriname,United States,2019,5.022,USD millions,Roland Kpodar (IMF),North America,SUR,USA,5.256434e+03,2.015964e+07,8677.305220,61047.964820
3976,Suriname,United States,2020,3.275,USD millions,Roland Kpodar (IMF),North America,SUR,USA,4.416708e+03,1.972358e+07,7213.107667,59484.033550
3977,Suriname,Vietnam,2018,1.401,USD millions,Roland Kpodar (IMF),Asia,SUR,VNM,5.195769e+03,2.933586e+05,8666.648707,3048.283276
3978,Suriname,Vietnam,2019,1.453,USD millions,Roland Kpodar (IMF),Asia,SUR,VNM,5.256434e+03,3.149476e+05,8677.305220,3241.076490
3979,Suriname,Vietnam,2020,1.8860000000000001,USD millions,Roland Kpodar (IMF),Asia,SUR,VNM,4.416708e+03,3.239722e+05,7213.107667,3303.169498

In [18]:
# Filter for Kenya as receiving country in 2024
kenya_2024 = df[(df['Receiving_Country'] == 'Kenya')]


# Change United States to Kenya value to 2,637,772.27
kenya_2024.loc[kenya_2024['Sending_Country'] == 'United States', 'Value'] = "2,637,772.27"
# Display all entries
print(f"Total number of entries: {len(kenya_2024)}")
print(f"\nAll Value entries for Kenya in 2024:\n")
print(kenya_2024[['Sending_Country', 'Receiving_Country', 'Year', 'Value','Source']].to_string())

# Convert Value column to numeric (removing commas) and calculate sum
kenya_2024['Value_numeric'] = kenya_2024['Value'].astype(str).str.replace(',', '').astype(float)


total_sum = kenya_2024['Value_numeric'].sum()

print(f"\n\nTotal sum of all Value entries: {total_sum:,.2f} USD millions")

Total number of entries: 40

All Value entries for Kenya in 2024:

           Sending_Country Receiving_Country  Year                 Value                 Source
2                Australia             Kenya  2024     184,497.099695719  Central Bank of Kenya
4                  Austria             Kenya  2024      13,169.065145833  Central Bank of Kenya
5                  Bahamas             Kenya  2024       1,453.632639905  Central Bank of Kenya
6                  Bahrain             Kenya  2024       5,004.769090469  Central Bank of Kenya
8                  Belgium             Kenya  2024      22,844.654997935  Central Bank of Kenya
16                  Canada             Kenya  2024      130,812.76972775  Central Bank of Kenya
22                   China             Kenya  2024       5,981.681937719  Central Bank of Kenya
27           Côte d'Ivoire             Kenya  2024       4,351.233359615  Central Bank of Kenya
32                   Egypt             Kenya  2024       2,710.849916951  Central Bank of Kenya
34                  France             Kenya  2024      25,420.562300568  Central Bank of Kenya
39                 Germany             Kenya  2024     197,764.185703727  Central Bank of Kenya
45                   India             Kenya  2024      20,594.869099147  Central Bank of Kenya
47                    Iraq             Kenya  2024      18,473.974825301  Central Bank of Kenya
50                   Italy             Kenya  2024      33,857.169027017  Central Bank of Kenya
54                   Japan             Kenya  2024       6,019.671359217  Central Bank of Kenya
62                  Malawi             Kenya  2024       2,348.468507446  Central Bank of Kenya
66                 Namibia             Kenya  2020           22.27557275  Central Bank of Kenya
68             New Zealand             Kenya  2024       2,997.798884179  Central Bank of Kenya
70                 Nigeria             Kenya  2024       7,235.873538576  Central Bank of Kenya
72                  Norway             Kenya  2024      20,219.725544913  Central Bank of Kenya
75                    Oman             Kenya  2024       8,642.361559321  Central Bank of Kenya
79                   Qatar             Kenya  2024      69,232.138058795  Central Bank of Kenya
83            Saudi Arabia             Kenya  2024      404,105.02454433  Central Bank of Kenya
88            South Africa             Kenya  2024      24,095.095706679  Central Bank of Kenya
92             South Sudan             Kenya  2024       5,789.706224355  Central Bank of Kenya
99                  Sweden             Kenya  2024      18,233.930534005  Central Bank of Kenya
103            Switzerland             Kenya  2024      51,518.222344458  Central Bank of Kenya
105               Tanzania             Kenya  2024      75,845.291390990  Central Bank of Kenya
106        The Netherlands             Kenya  2024      31,220.545359899  Central Bank of Kenya
111                 Uganda             Kenya  2024      64,988.791356259  Central Bank of Kenya
113   United Arab Emirates             Kenya  2024     137,814.495861864  Central Bank of Kenya
118         United Kingdom             Kenya  2024     358,836.441397577  Central Bank of Kenya
123          United States             Kenya  2024          2,637,772.27  Central Bank of Kenya
127                 Zambia             Kenya  2024       8,091.510769618  Central Bank of Kenya
2789               Georgia             Kenya  2018              0.065257    Roland Kpodar (IMF)
2790               Georgia             Kenya  2019              0.036446    Roland Kpodar (IMF)
2791               Georgia             Kenya  2020  0.020257999999999998    Roland Kpodar (IMF)
3623           Philippines             Kenya  2018                   0.0    Roland Kpodar (IMF)
3624           Philippines             Kenya  2019                   0.0    Roland Kpodar (IMF)
3625           Philippines             Kenya  2020                   0.0    Roland Kpodar (IMF)


Total sum of all Value entries: 4,601,966.28 USD millions

C:\Users\clint\AppData\Local\Temp\ipykernel_20636\867313297.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kenya_2024['Value_numeric'] = kenya_2024['Value'].astype(str).str.replace(',', '').astype(float)

In [19]:
kenya_2024

,Sending_Country,Receiving_Country,Year,Value,Unit,Source,Region,Sending_Country_Code,Receiving_Country_Code,Sending_Country_GDP,Receiving_Country_GDP,Sending_Country_GDP_Per_Capita,Receiving_Country_GDP_Per_Capita,Value_numeric
2,Australia,Kenya,2024,"184,497.099695719",USD millions,Central Bank of Kenya,Africa,AUS,KEN,1.665258e+06,104575.203136,61211.896760,1853.087855,1.844971e+05
4,Austria,Kenya,2024,"13,169.065145833",USD millions,Central Bank of Kenya,Africa,AUT,KEN,4.181904e+05,104575.203136,45562.040690,1853.087855,1.316907e+04
5,Bahamas,Kenya,2024,"1,453.632639905",USD millions,Central Bank of Kenya,Africa,BHS,KEN,1.363094e+04,104575.203136,33968.386340,1853.087855,1.453633e+03
6,Bahrain,Kenya,2024,"5,004.769090469",USD millions,Central Bank of Kenya,Africa,BHR,KEN,4.117271e+04,104575.203136,25916.464160,1853.087855,5.004769e+03
8,Belgium,Kenya,2024,"22,844.654997935",USD millions,Central Bank of Kenya,Africa,BEL,KEN,5.325307e+05,104575.203136,44837.724270,1853.087855,2.284465e+04
16,Canada,Kenya,2024,"130,812.76972775",USD millions,Central Bank of Kenya,Africa,CAN,KEN,1.833285e+06,104575.203136,44401.715390,1853.087855,1.308128e+05
22,China,Kenya,2024,"5,981.681937719",USD millions,Central Bank of Kenya,Africa,CHN,KEN,1.848811e+07,104575.203136,13121.676990,1853.087855,5.981682e+03
27,Côte d'Ivoire,Kenya,2024,"4,351.233359615",USD millions,Central Bank of Kenya,Africa,CIV,KEN,7.634667e+04,104575.203136,2390.747106,1853.087855,4.351233e+03
32,Egypt,Kenya,2024,"2,710.849916951",USD millions,Central Bank of Kenya,Africa,EGY,KEN,4.821898e+05,104575.203136,4137.609292,1853.087855,2.710850e+03
34,France,Kenya,2024,"25,420.562300568",USD millions,Central Bank of Kenya,Africa,FRA,KEN,2.702385e+06,104575.203136,39441.261050,1853.087855,2.542056e+04
39,Germany,Kenya,2024,"197,764.185703727",USD millions,Central Bank of Kenya,Africa,DEU,KEN,3.683560e+06,104575.203136,44108.701260,1853.087855,1.977642e+05
45,India,Kenya,2024,"20,594.869099147",USD millions,Central Bank of Kenya,Africa,IND,KEN,3.477476e+06,104575.203136,2396.712719,1853.087855,2.059487e+04
47,Iraq,Kenya,2024,"18,473.974825301",USD millions,Central Bank of Kenya,Africa,IRQ,KEN,1.924693e+05,104575.203136,4180.296195,1853.087855,1.847397e+04
50,Italy,Kenya,2024,"33,857.169027017",USD millions,Central Bank of Kenya,Africa,ITA,KEN,2.029013e+06,104575.203136,34398.197610,1853.087855,3.385717e+04
54,Japan,Kenya,2024,"6,019.671359217",USD millions,Central Bank of Kenya,Africa,JPN,KEN,4.605055e+06,104575.203136,37144.914270,1853.087855,6.019671e+03
62,Malawi,Kenya,2024,"2,348.468507446",USD millions,Central Bank of Kenya,Africa,MWI,KEN,1.196445e+04,104575.203136,552.495385,1853.087855,2.348469e+03
66,Namibia,Kenya,2020,22.27557275,USD millions,Central Bank of Kenya,Africa,NAM,KEN,1.033518e+04,84035.138347,3787.499440,1609.334141,2.227557e+01
68,New Zealand,Kenya,2024,"2,997.798884179",USD millions,Central Bank of Kenya,Africa,NZL,KEN,2.211008e+05,104575.203136,41416.284890,1853.087855,2.997799e+03
70,Nigeria,Kenya,2024,"7,235.873538576",USD millions,Central Bank of Kenya,Africa,NGA,KEN,5.695153e+05,104575.203136,2447.638697,1853.087855,7.235874e+03
72,Norway,Kenya,2024,"20,219.725544913",USD millions,Central Bank of Kenya,Africa,NOR,KEN,4.439437e+05,104575.203136,79670.142000,1853.087855,2.021973e+04
75,Oman,Kenya,2024,"8,642.361559321",USD millions,Central Bank of Kenya,Africa,OMN,KEN,9.145359e+04,104575.203136,17315.711060,1853.087855,8.642362e+03
79,Qatar,Kenya,2024,"69,232.138058795",USD millions,Central Bank of Kenya,Africa,QAT,KEN,1.777246e+05,104575.203136,62188.827860,1853.087855,6.923214e+04
83,Saudi Arabia,Kenya,2024,"404,105.02454433",USD millions,Central Bank of Kenya,Africa,SAU,KEN,8.795836e+05,104575.203136,24917.186010,1853.087855,4.041050e+05
88,South Africa,Kenya,2024,"24,095.095706679",USD millions,Central Bank of Kenya,Africa,ZAF,KEN,3.654148e+05,104575.203136,5708.964422,1853.087855,2.409510e+04
92,South Sudan,Kenya,2024,"5,789.706224355",USD millions,Central Bank of Kenya,Africa,SSD,KEN,NaN,104575.203136,NaN,1853.087855,5.789706e+03
99,Sweden,Kenya,2024,"18,233.930534005",USD millions,Central Bank of Kenya,Africa,SWE,KEN,5.804465e+05,104575.203136,54916.030390,1853.087855,1.823393e+04
103,Switzerland,Kenya,2024,"51,518.222344458",USD millions,Central Bank of Kenya,Africa,CHE,KEN,8.111099e+05,104575.203136,89783.128140,1853.087855,5.151822e+04
105,Tanzania,Kenya,2024,"75,845.291390990",USD millions,Central Bank of Kenya,Africa,TZA,KEN,7.446323e+04,104575.203136,1120.774170,1853.087855,7.584529e+04
106,The Netherlands,Kenya,2024,"31,220.545359899",USD millions,Central Bank of Kenya,Africa,NLD,KEN,9.261823e+05,104575.203136,51471.049630,1853.087855,3.122055e+04
111,Uganda,Kenya,2024,"64,988.791356259",USD millions,Central Bank of Kenya,Africa,UGA,KEN,4.935700e+04,104575.203136,986.842075,1853.087855,6.498879e+04
113,United Arab Emirates,Kenya,2024,"137,814.495861864",USD millions,Central Bank of Kenya,Africa,ARE,KEN,4.624044e+05,104575.203136,42512.197170,1853.087855,1.378145e+05
118,United Kingdom,Kenya,2024,"358,836.441397577",USD millions,Central Bank of Kenya,Africa,GBR,KEN,3.271967e+06,104575.203136,47265.000950,1853.087855,3.588364e+05
123,United States,Kenya,2024,"2,637,772.27",USD millions,Central Bank of Kenya,Africa,USA,KEN,2.267949e+07,104575.203136,66682.614700,1853.087855,2.637772e+06
127,Zambia,Kenya,2024,"8,091.510769618",USD millions,Central Bank of Kenya,Africa,ZMB,KEN,2.869582e+04,104575.203136,1346.276489,1853.087855,8.091511e+03
2789,Georgia,Kenya,2018,0.065257,USD millions,Roland Kpodar (IMF),Africa,GEO,KEN,1.756566e+04,80165.208728,4713.653548,1596.690459,6.525700e-02
2790,Georgia,Kenya,2019,0.036446,USD millions,Roland Kpodar (IMF),Africa,GEO,KEN,1.851082e+04,84264.984851,4975.811482,1645.709618,3.644600e-02
2791,Georgia,Kenya,2020,0.020257999999999998,USD millions,Roland Kpodar (IMF),Africa,GEO,KEN,1.734640e+04,84035.138347,4659.609253,1609.334141,2.025800e-02
3623,Philippines,Kenya,2018,0.0,USD millions,Roland Kpodar (IMF),Africa,PHL,KEN,3.733791e+05,80165.208728,3410.936480,1596.690459,0.000000e+00
3624,Philippines,Kenya,2019,0.0,USD millions,Roland Kpodar (IMF),Africa,PHL,KEN,3.962244e+05,84264.984851,3575.881709,1645.709618,0.000000e+00
3625,Philippines,Kenya,2020,0.0,USD millions,Roland Kpodar (IMF),Africa,PHL,KEN,3.585106e+05,84035.138347,3198.666900,1609.334141,0.000000e+00

In [20]:
# Check unique sending countries
print("Unique sending countries in kenya_2024:")
print(kenya_2024['Sending_Country'].unique())

Unique sending countries in kenya_2024:
['Australia' 'Austria' 'Bahamas' 'Bahrain' 'Belgium' 'Canada' 'China'
 "Côte d'Ivoire" 'Egypt' 'France' 'Germany' 'India' 'Iraq' 'Italy' 'Japan'
 'Malawi' 'Namibia' 'New Zealand' 'Nigeria' 'Norway' 'Oman' 'Qatar'
 'Saudi Arabia' 'South Africa' 'South Sudan' 'Sweden' 'Switzerland'
 'Tanzania' 'The Netherlands' 'Uganda' 'United Arab Emirates'
 'United Kingdom' 'United States' 'Zambia' 'Georgia' 'Philippines']

In [21]:
# Filter for North American countries only
north_american_countries = ['United States', 'Canada', 'Mexico']

kenya_2024_north_america = kenya_2024[kenya_2024['Sending_Country'].isin(north_american_countries)]

print(f"Total entries from North America to Kenya: {len(kenya_2024_north_america)}")
print(f"\nRemittances from North America to Kenya:\n")
print(kenya_2024_north_america[['Sending_Country', 'Receiving_Country', 'Year', 'Value', 'Source']].to_string())

# Calculate total from North America
total_north_america = kenya_2024_north_america['Value_numeric'].sum()
print(f"\n\nTotal remittances from North America: {total_north_america:,.2f} USD millions")

Total entries from North America to Kenya: 2

Remittances from North America to Kenya:

    Sending_Country Receiving_Country  Year             Value                 Source
16           Canada             Kenya  2024  130,812.76972775  Central Bank of Kenya
123   United States             Kenya  2024      2,637,772.27  Central Bank of Kenya


Total remittances from North America: 2,768,585.04 USD millions

In [22]:
diaspora_df = pd.read_csv(r'C:\Users\clint\Desktop\Remitances\Data\Diaspora Remittances.csv')
diaspora_df

,Year,Month,North America,Europe,Rest of World,Total Remittances (USD '000)
0,2025,1,"243,337.16","71,003.74","113,033.72","427,374.62"
1,2025,2,"215,577.36","70,853.91","95,813.43","382,244.71"
2,2025,3,"238,822.58","75,971.43","108,102.71","422,896.73"
3,2025,4,"252,027.72","71,627.24","99,236.35","422,891.30"
4,2025,5,"251,421.74","80,514.75","108,139.84","440,076.33"
...,...,...,...,...,...,...
256,2004,8,0.00,0.00,0.00,"28,894.00"
257,2004,9,0.00,0.00,0.00,"28,894.00"
258,2004,10,0.00,0.00,0.00,"25,223.00"
259,2004,11,0.00,0.00,0.00,"25,473.00"
260,2004,12,0.00,0.00,0.00,"29,130.00"

In [23]:
#isolate Year column 2024
diaspora_2024 = diaspora_df[diaspora_df['Year'] == 2024]
diaspora_2024

,Year,Month,North America,Europe,Rest of World,Total Remittances (USD '000)
9,2024,1,"227,764.71","85,970.23","98,675.10","412,410.04"
10,2024,2,"216,261.02","68,506.15","101,166.51","385,933.68"
11,2024,3,"229,327.94","70,459.26","107,984.99","407,772.19"
12,2024,4,"214,547.83","74,874.09","107,874.65","397,296.56"
13,2024,5,"226,417.81","68,225.28","109,804.30","404,447.39"
14,2024,6,"206,630.55","62,654.47","102,307.78","371,592.80"
15,2024,7,"227,532.70","73,721.62","113,003.32","414,257.64"
16,2024,8,"250,084.59","68,447.17","108,668.97","427,200.73"
17,2024,9,"243,361.37","70,484.84","104,649.09","418,495.31"
18,2024,10,"247,934.48","71,364.49","117,883.06","437,182.04"
19,2024,11,"242,877.06","71,350.29","109,021.52","423,248.87"
20,2024,12,"242,410.58","74,544.64","128,430.12","445,385.34"

In [24]:
# Convert string values to numeric (remove commas) and convert from thousands to millions
for col in ['North America', 'Europe', 'Rest of World', 'Total Remittances (USD \'000)']:
    diaspora_2024[col] = diaspora_2024[col].astype(str).str.replace(',', '').astype(float) / 1000

# Sum each value column
print("Sum of value columns for 2024 (in USD millions):\n")
print(f"North America: {diaspora_2024['North America'].sum():,.2f}")
print(f"Europe: {diaspora_2024['Europe'].sum():,.2f}")
print(f"Rest of World: {diaspora_2024['Rest of World'].sum():,.2f}")
print(f"Total Remittances (USD millions): {diaspora_2024['Total Remittances (USD \'000)'].sum():,.2f}")

Sum of value columns for 2024 (in USD millions):

North America: 2,775.15
Europe: 860.60
Rest of World: 1,309.47
Total Remittances (USD millions): 4,945.22

C:\Users\clint\AppData\Local\Temp\ipykernel_20636\1477996254.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diaspora_2024[col] = diaspora_2024[col].astype(str).str.replace(',', '').astype(float) / 1000
C:\Users\clint\AppData\Local\Temp\ipykernel_20636\1477996254.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diaspora_2024[col] = diaspora_2024[col].astype(str).str.replace(',', '').astype(float) / 1000
C:\Users\clint\AppData\Local\Temp\ipykernel_20636\1477996254.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diaspora_2024[col] = diaspora_2024[col].astype(str).str.replace(',', '').astype(float) / 1000
C:\Users\clint\AppData\Local\Temp\ipykernel_20636\1477996254.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diaspora_2024[col] = diaspora_2024[col].astype(str).str.replace(',', '').astype(float) / 1000